# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inputdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InputDialog(object):
    def setupUi(self, InputDialog):
        InputDialog.setObjectName("InputDialog")
        InputDialog.resize(251, 79)
        self.buttonBox = QtWidgets.QDialogButtonBox(InputDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 50, 231, 21))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.textEdit = QtWidgets.QTextEdit(InputDialog)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 231, 31))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(InputDialog)
        self.buttonBox.accepted.connect(InputDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(InputDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(InputDialog)

    def retranslateUi(self, InputDialog):
        _translate = QtCore.QCoreApplication.translate
        InputDialog.setWindowTitle(_translate("InputDialog", "Dialog"))
